dshunt/urls.py
from django.contrib import admin
from django.urls import include, path

from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    # path('accounts/', include('django.contrib.auth.urls')),
    path("accounts/", include("allauth.urls")),
    path("user/<int:pk>/", views.UserProfileDetailsView.as_view(), name="user-profile"),
    path(
        "user/<int:pk>/update/",
        views.UserProfileUpdateView.as_view(),
        name="user-profile-update",
    ),
    path(
        "user/<int:pk>/submitted-list/",
        views.UserSubmittedListView.as_view(),
        name="user-submitted-post",
    ),
    path(
        "user/<int:pk>/upvoted-list/",
        views.UserUpvotedPostListView.as_view(),
        name="user-upvoted-post",
    ),
    path(
        "user/<int:pk>/approved-list/",
        views.UserApprovedPostListView.as_view(),
        name="user-approved-post",
    ),
    path(
        "user/<int:pk>/post-detail/",
        views.UserPostDetailView.as_view(),
        name="user-post-detail",
    ),
    path(
        "user/<int:pk>/collection-list/",
        views.UserCollectionListView.as_view(),
        name="user-collection-list",
    ),
    path(
        "user/<int:pk>/collection-detail/",
        views.UserCollectionDetailView.as_view(),
        name="user-collection-detail",
    ),
    # Post List
    path("", views.PostListHomeView.as_view(), name="root"),
    path("posts/", views.PostListView.as_view(), name="posts"),
    path(
        "posts/<int:year>/<int:month>/<int:day>/",
        views.PostListByDateView.as_view(month_format="%m"),
        name="posts-list-by-date",
    ),
    path("books/", views.BookListView.as_view(), name="book-list"),
    path("videos/", views.VideoListView.as_view(), name="video-list"),
    path("tutorials/", views.TutorialListView.as_view(), name="tutorial-list"),
    path(
        "podcast-episodes/", views.PodcastEpisodeListView.as_view(), name="podcast-list"
    ),
    # Post Submit
    path("post/", views.PostSubmitPageView.as_view(), name="post-submit"),
    path("books/new/", views.BookCreateView.as_view(), name="book-create"),
    path("videos/new/", views.VideoCreateView.as_view(), name="video-create"),
    path("tutorials/new/", views.tutotrial_create, name="tutorial-create"),
    path(
        "podcast-episode/new/",
        views.PodcastEpisodeCreateView.as_view(),
        name="podcast-episode-create",
    ),
    # Post Detail
    path("posts/<int:pk>/", views.PostDetailView.as_view(), name="post-detail"),
    path(
        "posts/<int:pk>/comments/new/",
        views.CommentCreateView.as_view(),
        name="post-comment-create",
    ),
    # vote
    path("post/<int:id>/vote", views.Vote.as_view(), name="post-vote"),
    # Collection
    path("collections/", views.collection_list_view, name="collection-list"),
    path(
        "collections/<int:pk>/", views.collection_detail_view, name="collection-detail"
    ),
    path("collections/new/", views.collection_create_view, name="collection-create"),
    path(
        "collections/<int:pk>/post/new/",
        views.add_post_to_collection_view,
        name="add-to-collection",
    ),
    path(
        "collections/staff-pick/",
        views.staff_pick_collection_list,
        name="staff-pick-collection",
    ),
    # category
    path("category/", views.category, name="category"),
    # challenges
    path("challenges/", views.challenges, name="challenges"),
]

dshunt/models.py
from django.contrib.auth import get_user_model
from django.contrib.auth.models import AbstractUser
from django.contrib.postgres.fields import ArrayField
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

# ---------------- User ---------------- #


class AppUser(AbstractUser):
    pass


class UserProfile(models.Model):
    user = models.OneToOneField(AppUser, on_delete=models.CASCADE)
    headline = models.CharField(
        max_length=255,
    )
    avatar = models.ImageField(upload_to="user_avatar/", blank=True, null=True)
    website = models.URLField(blank=True, null=True)
    twitter_profile = models.CharField(max_length=50, blank=True, null=True)
    github_profile = models.CharField(max_length=50, blank=True, null=True)
    linkedin = models.URLField(blank=True, null=True)
    youtube_channel = models.URLField(blank=True, null=True)

    def __str__(self):
        return str(self.headline)

    def get_absolute_url(self):
        return reverse("user-profile", kwargs={"pk": self.user.pk})


# ------------- POSTS -------------- #


class Category(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Challenges(models.Model):
    name = models.CharField(max_length=100)
    link = models.URLField(blank=True, null=True)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Channel(models.Model):
    name = models.CharField(max_length=100)
    link = models.URLField(blank=True, null=True)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Podcast(models.Model):
    name = models.CharField(max_length=100)
    link = models.URLField(blank=True, null=True)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class PostType(models.TextChoices):
    BOOK = "book", _("Book")
    VIDEO = "video", _("Video")
    TUTORIAL = "tutorial", _("Tutorial")
    PODCAST = "podcast", _("Podcast")


class Post(models.Model):
    post_type = models.CharField(max_length=20, choices=PostType.choices)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    description = models.TextField()
    tags = ArrayField(models.CharField(max_length=255), default=list)
    link = models.URLField(blank=True, null=True)
    author = models.CharField(max_length=255, blank=True, null=True)
    channel = models.ForeignKey(
        Channel, on_delete=models.CASCADE, blank=True, null=True
    )
    podcast = models.ForeignKey(
        Podcast, on_delete=models.CASCADE, blank=True, null=True
    )
    published_at = models.DateTimeField(blank=True, null=True)
    approved_at = models.DateTimeField(blank=True, null=True)
    created_user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    approved = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    total_votes = models.IntegerField(null=False, default=0, blank=False)

    def __str__(self):
        return "{}-{}".format(self.title, self.approved)

    def get_vote_count(self):
        return self.total_votes

    def is_voted(self, user):
        voted = self.postvote_set.filter(created_user=user).exists()
        return voted

    def save(
        self, force_insert=False, force_update=False, using=None, update_fields=None
    ):
        from django.utils import timezone

        if self.pk:
            p = Post.objects.get(pk=self.pk)
            if not p.approved and self.approved:
                self.approved_at = timezone.now()
        else:
            self.published_at = timezone.now()

        return super().save(
            force_insert=False, force_update=False, using=None, update_fields=None
        )


class PostVote(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    created_user = models.ForeignKey(
        get_user_model(), on_delete=models.CASCADE, blank=True, null=True
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.post.title


class PostComment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.TextField()
    created_user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        from django.urls import reverse_lazy

        return reverse_lazy("post-detail", kwargs={"pk": self.post.pk})

    def is_commented(self, user):
        return self.created_user.id == user.id


class Collection(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    posts = models.ManyToManyField(Post)
    is_staffpick = models.BooleanField(default=False)
    is_public = models.BooleanField(default=False)
    created_user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


# Proxy Models


class PostQuerySet(models.QuerySet):
    def all(self):
        return self.filter(approved=True)

    def sorted_by_upvotes(self):
        return self.order_by("-total_votes")


class PostManager(models.Manager):
    def get_queryset(self):
        return PostQuerySet(self.model, using=self._db).all()


class BookManager(models.Manager):
    def get_queryset(self):
        return PostQuerySet(self.model, using=self._db).filter(post_type=PostType.BOOK)


class VideoManager(models.Manager):
    def get_queryset(self):
        return PostQuerySet(self.model, using=self._db).filter(post_type=PostType.VIDEO)


class TutorialManager(models.Manager):
    def get_queryset(self):
        return PostQuerySet(self.model, using=self._db).filter(
            post_type=PostType.TUTORIAL
        )


class PodcastManager(models.Manager):
    def get_queryset(self):
        return PostQuerySet(self.model, using=self._db).filter(
            post_type=PostType.PODCAST
        )


class Book(Post):
    class Meta:
        proxy = True

    objects = BookManager()


class Video(Post):
    objects = VideoManager()

    class Meta:
        proxy = True

    def get_absolute_url(self):
        return reverse("post-submit")


class Tutorial(Post):
    class Meta:
        proxy = True

    objects = TutorialManager()


class PodcastEpisode(Post):
    class Meta:
        proxy = True

    def get_absolute_url(self):
        return reverse("post-submit")

    objects = PodcastManager()

dshunt/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from .models import AppUser, UserProfile, Post, Book, Video, Tutorial, PodcastEpisode, PostType
from .models import (Podcast, Channel, PostComment, Collection)


class AppUserCreationForm(UserCreationForm):
    
    class Meta:
        model = AppUser
        fields = ['username']


class AppUserChangeForm(UserChangeForm):
    
    class Meta:
        model = AppUser
        fields = ['email']


class UserProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = [
            'headline',
            'avatar',
            'website',
            'twitter_profile',
            'github_profile',
            'linkedin',
            'youtube_channel',
        ]


class PostTypeForm(forms.Form):
    post_type = forms.ChoiceField(choices=PostType.choices)


class BookCreateForm(forms.ModelForm):
    author = forms.CharField()
    link = forms.URLField()

    class Meta:
        model = Book
        fields = (
            'category',
            'title',
            'description',
            'author',
            'link',
            'tags'
        )


class VideoCreateForm(forms.ModelForm):
    channel = forms.ModelChoiceField(queryset=Channel.objects.all())
    link = forms.URLField()

    class Meta:
        model = Video
        fields = (
            'category',
            'title',
            'description',
            'link',
            'channel',
            'tags'
        )


class TutorialCreateForm(forms.ModelForm):
    author = forms.CharField()
    link = forms.URLField()

    class Meta:
        model = Tutorial
        fields = (
            'category',
            'title',
            'description',
            'channel',
            'link',
            'author',
            'tags'
        )


class PodcastEpisodeCreateForm(forms.ModelForm):
    podcast = forms.ModelChoiceField(queryset=Podcast.objects.all())
    link = forms.URLField()

    class Meta:
        model = PodcastEpisode
        fields = (
            'category',
            'title',
            'description',
            'link',
            'tags',
            'podcast'
        )


class CommentForm(forms.ModelForm):
    content = forms.CharField(widget=forms.Textarea(attrs={'cols': 50, 'rows': 3}))

    class Meta:
        model = PostComment
        fields = (
            'content',
        )


class CollectionForm(forms.ModelForm):

    class Meta:
        model = Collection
        fields = (
            'title',
            'description',
            'posts',
            'is_staffpick',
            'is_public'
        )

    def clean_title(self):
        title = self.cleaned_data.get('title')
        cols = Collection.objects.filter(title__iexact=title).select_related()
        if cols.exists():
            raise forms.ValidationError("Title already exists")
        return title


class AddtoCollectionForm(forms.Form):
    post = forms.ModelChoiceField(queryset=Post.objects.filter(approved=True))


class CollectionListForm(forms.Form):
    collection = forms.ModelChoiceField(queryset=Collection.objects.all())

templates/dshunt/user/user_collection_detail.html
{% extends 'base2.html' %}
{% load crispy_forms_tags %}

{% block main %}
  <h2>Collection Detail</h2>

{{ add_to_coll_form.errors }}

<!--Modal to add post to collection-->

<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#addPostModal">
  Add Post
</button>

<!-- Modal -->
<div class="modal fade" id="addPostModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Add Post to {{ collection.title }}</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
        <form method="post" action="/collections/{{ collection.pk }}/post/new/?model=collection">
          <div class="modal-body">
              {% csrf_token %}
            {{ add_to_coll_form|crispy }}
          </div>
          <div class="modal-footer">
<!--            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>-->
            <button type="submit" class="btn btn-primary">Add Post</button>
          </div>
        </form>
      </div>
    </div>
  </div>

  <div class="p-4">
    <p>Title: {{ collection.title }}</p>
    <p>Description: {{ collection.description }}</p>
    <p>is_staffpick: {{ collection.is_staffpick }}</p>
    <p>is_public: {{ collection.is_public }}</p>
<!--    <p>Created User: {{ collection.created_user }}</p>-->
    <p>Created At: {{ collection.created_at }}</p>
    <p>Post count: {{ posts_count }}</p>
    <p>Posts
    {% if collection.posts %}
      <div>
        <ul>
          {% for object in post_list %}
            {% include 'dshunt/post_list/post.html' with from_user_profile=True %}
          {% endfor %}
        </ul>
      </div>
    {% endif %}
    </p>
  </div>

{% include 'dshunt/pagination.html' %}

{% endblock %}

templates/dshunt/user/user_collection_list.html
{% extends 'base2.html' %}

{% block main %}
  <h2>Collections</h2>
<!--  <a href="{% url 'collection-create' %}"><button>Create Collection</button></a>-->
  <ul>
    {% for object in page_obj.object_list %}
      <li>
        <ol type="1">
          <li>{{ object.title }}</li>
          <li>{{ object.description }}</li>
          <li>{{ object.is_staffpick }}</li>
          <li>{{ object.is_public }}</li>
          <li>{{ object.created_user }}</li>
          <li>{{ object.created_at }}</li>
          <li><a href="{% url 'user-collection-detail' object.id %}"><button>View</button></a></li>
        </ol>
      </li>
    {% empty %}
    <h5>No collections exists !</h5>
    {% endfor %}
  </ul>

<!-- Pagination -->
{% include 'dshunt/pagination.html' %}

{% endblock %}

templates/dshunt/user/user_post.html
    <li>Post Type: {{ object.get_post_type_display }}</li>
    <li>Category: {{ object.category.name }}</li>
    <li>Title: {{ object.title }}</li>
    <li>Description: {{ object.description }}</li>
    <li>Tags: {{ object.tags }}</li>
    <li>Link: {{ object.link }}</li>
    <li>Author: {{ object.author }}</li>
    <li>Channel: {{ object.channel }}</li>
    <li>Podcast: {{ object.podcast }}</li>
    <li>Podcast: {{ from_user_profile }}</li>

    <li>Votes: {{ object.total_votes }}</li>
    <li>Published Date: {{ object.published_at|date }}</li>

    {% if not from_post_detail %}
        <a href="{% url 'user-post-detail' object.id %}"><button>View</button></a>
    {% endif %}

    {% block add_to_collection %}
    {% endblock add_to_collection %}

templates/dshunt/user/user_post_detail.html
{% extends 'base2.html' %}

{% block main %}
    <h2>User Post Detail</h2>

    {% include 'dshunt/user/user_post.html' with from_post_detail=True %}

    <li>Comments Count: {{ comments_count }}</li>

        {% include 'dshunt/post_detail/post_comment_form.html' %}

        <div>
            <h3>Comments</h3>

            <ol type="1">
                {% for comment in comments %}
                    {% include 'dshunt/post_detail/post_comment.html' %}
                {% endfor %}
            </ol>

            {% if comments_count > 5 and comments|length == 5 %}
                <a href="?comment=all">view all</a>
            {% endif %}
        </div>
    </ul>

{% endblock main %}

templates/dshunt/user/user_post_list.html
{% extends 'base2.html' %}
{% load crispy_forms_tags %}

{% block content %}

<ul>
    {% for object in object_list %}
        {% include 'dshunt/user/user_post.html' %}
        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#addPostModal">
          Add To Collection
        </button>

<!-- Modal -->
<div class="modal fade" id="addPostModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Add To Collection</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
        <form method="post" action="/collections/{{ object.id }}/post/new/?model=post">
          <div class="modal-body">
              {% csrf_token %}
            {{ add_to_coll_form|crispy }}
          </div>
          <div class="modal-footer">
<!--            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>-->
            <button type="submit" class="btn btn-primary">Add Post</button>
          </div>
        </form>
      </div>
    </div>
  </div>
    {% endfor %}
</ul>


{% include 'dshunt/pagination.html' %}

{% endblock %}



{% block sidebar %}
<div class="section card mt-3 rounded-1">
    <div class="card-title mb-0 p-3 bg-light rounded-top">
        <span class="mb-0 h6 text-github"><b>Subscribe to The Daily</b></span>
    </div>
    <div class="card-body">
        <div class="wrapper">
            <p class='mb-3'>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore</p>

            <div class="w-100 d-flex justify-content-between">
                <div class="">
                <input type="text" class="form-control" placeholder="Your email eg. john@example.com" aria-label="Email Address">
                </div>
                <div class="">
                <button type="submit" class="btn btn-primary">Subscribe</button>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="section card mt-3 rounded-1">
    <div class="card-title mb-0 p-3 bg-light rounded-top">
        <span class="mb-0 h6 text-github"><b>What is Trending?</b></span>
    </div>
    <div class="card-body">
        <div class="wrapper">
            <div class='h6 fw-bold mb-3'>#learning-ml</div>

            <div class="d-flex align-items-center mb-2">
            <div class="flex-shrink-0">
                <svg class="bd-placeholder-img" width="80" height="80" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Image" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#e5e5e5"></rect><text x="50%" y="50%" fill="#999" dy=".3em">Image</text></svg>

            </div>
            <div class="flex-grow-1 ms-3 small">
                This is some content from a media component. You can replace this with any content.
            </div>
            </div>

            <div class="d-flex align-items-center">
            <div class="flex-shrink-0">
                <svg class="bd-placeholder-img" width="80" height="80" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Image" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#e5e5e5"></rect><text x="50%" y="50%" fill="#999" dy=".3em">Image</text></svg>

            </div>
            <div class="flex-grow-1 ms-3 small">
                This is some content from a media component. You can replace.
            </div>
            </div>

        </div>

        <div class="wrapper mt-4">
            <div class='h6 fw-bold mb-3'>#terradata</div>

            <div class="d-flex align-items-center mb-2">
            <div class="flex-shrink-0">
                <svg class="bd-placeholder-img" width="80" height="80" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Image" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#e5e5e5"></rect><text x="50%" y="50%" fill="#999" dy=".3em">Image</text></svg>

            </div>
            <div class="flex-grow-1 ms-3 small">
                This is some content from a media component. You can replace this with any content.
            </div>
            </div>

            <div class="d-flex align-items-center">
            <div class="flex-shrink-0">
                <svg class="bd-placeholder-img" width="80" height="80" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Image" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#e5e5e5"></rect><text x="50%" y="50%" fill="#999" dy=".3em">Image</text></svg>

            </div>
            <div class="flex-grow-1 ms-3 small">
                This is some content from a media component. You can replace.
            </div>
            </div>

        </div>

    </div>
</div>



<div class="section card mt-3 rounded-1">
    <div class="card-title p-3 bg-light rounded-top">
        <span class="mb-0 h6 text-github"><b>Have a question?</b></span>
    </div>
    <div class="card-body">
        <div class="wrapper">
                <p>Found a bug or have a question regarding the content?</p>
                <p>This site is maintained by me and you can reach me at <a href="#">support@dshunt.com</a></p>
        </div>
    </div>
</div>


<div class="section card mt-3 rounded-1">
    <div class="card-title p-3 bg-light rounded-top">
        <span class="mb-0 h6 text-github"><b>Follow Us</b></span>
    </div>
    <div class="card-body">
        <div class="wrapper"><a href="https://twitter.com/_flock_community"><i class="fab fa-twitter"></i>@_flock_community</a></div>
    </div>
</div>
{% endblock %}

templates/dshunt/user/user_profile_detail.html
{% extends 'base2.html' %}

{% block main %}
<a href="{% url 'user-profile-update' object.pk %}"><button>Update</button></a>
<ul>
  <li>Email: {{ object.user.email }}</li>
  <li>Headline: {{ object.headline }}</li>
  {% if object.avatar %}
  <li>Avatar: <img src="{{ 'object.avatar.url' }}" height="200px" width="200px"></li>
  {% else %}
  <li>Avatar: No avatar</li>
  {% endif %}
  <li>Website: {{ object.website }}</li>
  <li>Twitter profile: {{ object.twitter_profile }}</li>
  <li>Github profile: {{ object.github_profile }}</li>
  <li>Linked In: {{ object.linkedin }}</li>
  <li>Youtube Channel: {{ object.youtube_channel }}</li>

<!--  User's Post-->
  <br>
    <b>Post</b>
  <br>
  <li>Post Count: {{ post_count }}</li>
  <l1><a href="{% url 'user-approved-post' object.user.pk %}">View posts</a></l1>

  <br>
    <b>Collection</b>
  <br>
  <li>Collection Count: {{ collection_count }}</li>
  <l1><a href="{% url 'user-collection-list' object.user.pk %}">View collections</a></l1>


</ul>
{% endblock %}

templates/dshunt/user/user_update_form.html
{% extends 'base2.html' %}
{% load crispy_forms_tags %}

{% block main %}
<h2>User Profile Update</h2>

<form method="post" class="p-5">
    {% csrf_token %}
    {{ form | crispy }}
    <input type="submit" value="Update">
</form>

{% endblock %}